import { createUID } from '@/utils/index';

export const FAQ_DATA = [
  {
    id: createUID(),
    question: 'What is Lorem Ipsum?',
    answer: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry.',
  },
  {
    id: createUID(),
    question: 'Why do we use Lorem Ipsum?',
    answer:
      "It's used as placeholder text to demonstrate the visual presentation of documents or designs without the distraction of meaningful content.",
  },
  {
    id: createUID(),
    question: 'Where does it come from?',
    answer: 'The Lorem Ipsum text is derived from sections of a work by Cicero, written in 45 BC.',
  },
  {
    id: createUID(),
    question: 'How is Lorem Ipsum generated?',
    answer: "It's generated by jumbling parts of Cicero's work and doesn't carry any coherent meaning.",
  },
  {
    id: createUID(),
    question: 'Can I translate Lorem Ipsum?',
    answer:
      "Certainly, but as it's nonsensical, translating it might not yield any meaningful output in another language.",
  },
  {
    id: createUID(),
    question: 'Is Lorem Ipsum meaningful?',
    answer: "No, it's intentionally nonsensical and lacks any coherent message.",
  },
  {
    id: createUID(),
    question: 'Does Lorem Ipsum have any significance?',
    answer: "Primarily, it's used to fill spaces in visual representations and design mock-ups.",
  },
  {
    id: createUID(),
    question: 'Is Lorem Ipsum copyrighted?',
    answer: "No, as it's an uncopyrighted dummy text.",
  },
  {
    id: createUID(),
    question: 'Can Lorem Ipsum be patented?',
    answer: "No, it's a widely used and freely available text.",
  },
  {
    id: createUID(),
    question: 'Who uses Lorem Ipsum?',
    answer: 'Designers, developers, and those in publishing or graphic design fields frequently use Lorem Ipsum.',
  },
  {
    id: createUID(),
    question: 'Is Lorem Ipsum useful for content creation?',
    answer: "It's not appropriate for actual content creation, as it lacks any meaningful information.",
  },
  {
    id: createUID(),
    question: 'Are there variations of Lorem Ipsum?',
    answer:
      'Yes, there are several variations, altered versions, and humorous renditions created by different individuals.',
  },
  {
    id: createUID(),
    question: 'Is Lorem Ipsum always in Latin?',
    answer:
      'The classic Lorem Ipsum is in Latin, but variations might appear in different languages for diverse purposes.',
  },
  {
    id: createUID(),
    question: 'Can Lorem Ipsum be converted into a meaningful text?',
    answer: "No, it's intentionally constructed to lack a coherent message.",
  },
  {
    id: createUID(),
    question: 'How long has Lorem Ipsum been used?',
    answer: 'It has been used since the 1500s, tracing back to the printing industry.',
  },
  {
    id: createUID(),
    question: 'Is Lorem Ipsum always used in the same format?',
    answer: 'No, its usage can vary depending on the preferences and requirements of the user.',
  },
  {
    id: createUID(),
    question: 'Can I generate my Lorem Ipsum?',
    answer:
      'Yes, there are tools and generators available online that can create Lorem Ipsum text according to your specified length and variations.',
  },
  {
    id: createUID(),
    question: 'Is Lorem Ipsum ever used in serious documents?',
    answer: 'Rarely, as it lacks meaning and might diminish the credibility of serious content.',
  },
  {
    id: createUID(),
    question: 'Can Lorem Ipsum be used commercially?',
    answer: "Yes, it's freely available for both personal and commercial use.",
  },
  {
    id: createUID(),
    question: 'Does Lorem Ipsum ever change?',
    answer: 'While the classic version remains constant, variations and adaptations continue to emerge over time.',
  },
];
